name: fire_api
description: "A stripped down interface for firestore databases which allows both dart servers using `fire_api_dart` and flutter apps using `fire_api_flutter` to use the same api."
version: 1.1.9+2
repository: https://github.com/ArcaneArts/fire_api/tree/main/fire_api
environment:
  sdk: '>=3.0.0 <4.0.0'
dev_dependencies:
  lints: ^4.0.0
dependencies:
  fast_log: ^1.0.7
  rxdart: '>=0.27.7 <0.29.0'
