name: fire_api_flutter
description: "An implementation for fire_api for flutter apps using cloud_firestore."
version: 1.1.2+1
repository: https://github.com/ArcaneArts/firestore_api/tree/main/firestore_api_flutter
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  cloud_firestore: ">=4.0.0"
  fire_api: ^1.1.5
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter: